default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: rootpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: remote_line_development

test:
  <<: *default
  database: remote_line_test

production:
  <<: *default
  database: remote_line
  username: remote_line
  password: <%= ENV['REMOTE_LINE_DATABASE_PASSWORD'] %>
